name: k8s image sync

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gcr-image-sync:
    name: gcr.io image sync
    runs-on: ubuntu-latest
    steps:
    - name: sync
      uses: zhaolion/actions/gcr_images_sync@main
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: zhaolion
        images: https://raw.githubusercontent.com/zhaolion/gcr.io.images/master/images